# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exp_mean <- function(x, p, i, ncol, nrow, groups, group_sizes) {
    .Call('_singlecellmethods_exp_mean', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, groups, group_sizes)
}

log_vmr <- function(x, p, i, ncol, nrow, means, groups, group_sizes) {
    .Call('_singlecellmethods_log_vmr', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, means, groups, group_sizes)
}

normalizeCLR_dgc <- function(x, p, i, ncol, nrow, margin) {
    .Call('_singlecellmethods_normalizeCLR_dgc', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, margin)
}

scaleRowsWithStats_dgc <- function(x, p, i, mean_vec, sd_vec, ncol, nrow, thresh) {
    .Call('_singlecellmethods_scaleRowsWithStats_dgc', PACKAGE = 'singlecellmethods', x, p, i, mean_vec, sd_vec, ncol, nrow, thresh)
}

scaleRows_dgc <- function(x, p, i, ncol, nrow, thresh) {
    .Call('_singlecellmethods_scaleRows_dgc', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, thresh)
}

rowMeansWeighted_dgc <- function(x, p, i, weights, ncol, nrow) {
    .Call('_singlecellmethods_rowMeansWeighted_dgc', PACKAGE = 'singlecellmethods', x, p, i, weights, ncol, nrow)
}

rowSDs_dgc <- function(x, p, i, mean_vec, ncol, nrow) {
    .Call('_singlecellmethods_rowSDs_dgc', PACKAGE = 'singlecellmethods', x, p, i, mean_vec, ncol, nrow)
}

rowSDsWeighted_dgc <- function(x, p, i, mean_vec, weights, ncol, nrow) {
    .Call('_singlecellmethods_rowSDsWeighted_dgc', PACKAGE = 'singlecellmethods', x, p, i, mean_vec, weights, ncol, nrow)
}

cosine_normalize_cpp <- function(V, dim) {
    .Call('_singlecellmethods_cosine_normalize_cpp', PACKAGE = 'singlecellmethods', V, dim)
}

soft_kmeans_cpp <- function(Y, Z, max_iter, sigma) {
    .Call('_singlecellmethods_soft_kmeans_cpp', PACKAGE = 'singlecellmethods', Y, Z, max_iter, sigma)
}

merge_redundant_clusters <- function(R, thresh = 0.8) {
    .Call('_singlecellmethods_merge_redundant_clusters', PACKAGE = 'singlecellmethods', R, thresh)
}

