# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exp_mean <- function(x, p, i, ncol, nrow, groups, group_sizes) {
    .Call('_singlecellmethods_exp_mean', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, groups, group_sizes)
}

log_vmr <- function(x, p, i, ncol, nrow, means, groups, group_sizes) {
    .Call('_singlecellmethods_log_vmr', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, means, groups, group_sizes)
}

normalizeCLR_dgc <- function(x, p, i, ncol, nrow, margin) {
    .Call('_singlecellmethods_normalizeCLR_dgc', PACKAGE = 'singlecellmethods', x, p, i, ncol, nrow, margin)
}

